### ISSUE TITLE
Fresh install error IsCompilance

### ISSUE THREAD

**Issue by tycoonslive** [LoicVeirman/Hello-My-Dir#11]
Install fresh
Script launch .\Invoke-HelloMyDir.ps1
filling options
launch script again
An error with the request to launch -UpdateConfigeFile
![error](https://github.com/user-attachments/assets/8b7c6d3f-6456-43b9-9fad-73cfb5748189)

**Comment by LoicVeirman** [comment]
New release delivered. Pb fixed - and some improvement, get a look to the documentation ;)
