### ISSUE TITLE
Installation fails on windows 2022 eval

### ISSUE THREAD

**Issue by tmap** [LoicVeirman/Hello-My-Dir#13]
**Describe the bug**
When installing on a fresh eval version of windows 2022, standard installation fails.

**Screenshots**
![image](https://github.com/user-attachments/assets/9096a844-e5b3-484d-8a31-ea5526249b9a)

**Additional context**
Installed a fresh windows 2022 iso VM from MS.
Set ip address and dns to reach internet.

Then:
New-Item "C:\Scripts" -ItemType Directory
cd "c:\scripts\"
Invoke-WebRequest -Uri "https://github.com/LoicVeirman/Hello-My-Dir/archive/refs/tags/v1.1.2.1.zip" -OutFile "HelloMyDir-v1.1.2.zip"
Expand-Archive .\HelloMyDir-v1.1.2.zip
cd .\HelloMyDir-v1.1.2\Hello-My-Dir-1.1.2\
.\Invoke-HelloMyDir.ps1

at second .\Invoke-HelloMyDir.ps1 when installation fails it throws errors

**Comment by LoicVeirman** [comment]
As you may have noticed, the installation has been processed.
We are working on the issue reporting an “error” when the binaries are in fact installed.

**Comment by tmap** [comment]
yes, and thanks for the rapid response @LoicVeirman

**Comment by LoicVeirman** [comment]
New release delivered. Pb fixed - and some improvement, get a look to the documentation ;)
