### ISSUE TITLE
Missing Parameter names in line 579

### ISSUE THREAD

**Issue by flo313** [LoicVeirman/Hello-My-Dir#6]
**Describe the bug**
It miss paramater names in line 579 of script Invoke-HelloMyDIR.ps1. This make the WindowsFeature installation alerting as Error instead of success as it is the case

**To Reproduce**
1. Use a brand new fresh Windows 2022 (or 2025) Datacenter Server installation and run script.

**Expected behavior**
Have real WindowsFeature installation state.

**Desktop (please complete the following information):**
OS Name:                   Microsoft Windows Server 2022 Datacenter
OS Version:                10.0.20348 N/A Build 20348

**Additional context**
Solution: replace line 579 of script Invoke-HelloMyDIR.ps1 
'Write-Progression -Step Update success $CursorPosition' by 'Write-Progression -Step Update -code success -CursorPosition $CursorPosition'

**Comment by LoicVeirman** [comment]
Function uses positional arguments, so this is not the pb here. Removing *-Step* will be more accurate and less code typing.

**Comment by LoicVeirman** [comment]
Fix applied, and a new release has been pushed (1.1.2.1). Thanx flo'.

**Comment by flo313** [comment]
As you want 👍

Regards,
Flo

Le 2 septembre 2024 17:53:22 GMT+02:00, Loic Veirman ***@***.***> a écrit :

**Comment by LoicVeirman** [comment]
Pb is still present, will work on it to resolve once for all.
