### ISSUE TITLE
Angry ou Hungry

### ISSUE THREAD

**Issue by jmthia** [LoicVeirman/Hello-My-Dir#8]
Bonjour Loïc,
**Describe the bug**
Pas vraiment un bug... car cela peut être intentionnel. Dans le User manual 1.1.0

Angry to learn how this works? 

C'est bien faché qu'il lire. J'aurai mis Hungry.

En tout cas merci pour le boulot et la partage.
Jean Marie

**Comment by LoicVeirman** [comment]
Et tu aurais eu parfaitement raison ! Merci de m’avoir mis le nez dessus 😉

De : jmthia ***@***.***>
Date : jeudi, 26 septembre 2024 à 18:23
À : LoicVeirman/Hello-My-Dir ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [LoicVeirman/Hello-My-Dir] Angry ou Hungry (Issue #8)

CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

Bonjour Loïc,
Describe the bug
Pas vraiment un bug... car cela peut être intentionnel. Dans le User manual 1.1.0

Angry to learn how this works?

C'est bien faché qu'il lire. J'aurai mis Hungry.

En tout cas merci pour le boulot et la partage.
Jean Marie

**Comment by LoicVeirman** [comment]
Corrigé dans la ligne main.
