### ISSUE TITLE
Error On windows Server 2025 Install-binaries

### ISSUE THREAD

**Issue by JM2K69** [LoicVeirman/Hello-My-Dir#9]
**Describe the bug**
During the first stage to install binaries the script return error on installing binarres

Windows Server Version : 2025
OS Install English with french keyboard

![image](https://github.com/user-attachments/assets/1655aadd-149f-49ae-a532-c0eeeeb205f6)
In Powershell command `Get-EventLog -LogName "HelloMyDir" | fl`

```
Index              : 9
EntryType          : Information
InstanceId         : 0
Message            : USE CASE: The domain is to be installed

                     Error: Parameter set cannot be resolved using the specified named parameters.

                     Error: Parameter set cannot be resolved using the specified named parameters.

                     Error: Parameter set cannot be resolved using the specified named parameters.

                     Error: Parameter set cannot be resolved using the specified named parameters.

                     Error: Parameter set cannot be resolved using the specified named parameters.
                     Installation completed. The server will now reboot.

Category           : (0)
CategoryNumber     : 0
ReplacementStrings : {USE CASE: The domain is to be installed

                     Error: Parameter set cannot be resolved using the specified named parameters.

                     Error: Parameter set cannot be resolved using the specified named parameters.

                     Error: Parameter set cannot be resolved using the specified named parameters.

                     Error: Parameter set cannot be resolved using the specified named parameters.

                     Error: Parameter set cannot be resolved using the specified named parameters.
                     Installation completed. The server will now reboot.
                     }
Source             : HmD_Invoke-HelloMyDIR
TimeGenerated      : 09/10/2024 14:30:42
TimeWritten        : 09/10/2024 14:30:42
UserName           :

Index              : 8
EntryType          : Information
InstanceId         : 0
Message            : GENERATE NEW COMPLEX RANDOM PASSWORD
                     -----------
                     Parameter Length: 24
                     Parameter AsClearText: True

                     Default settings: at least 2 special char, 2 digits and 2 letters.

                     round 12: Quotas reinitialized.

                     final: password kept as clear text.

Category           : (0)
CategoryNumber     : 0
ReplacementStrings : {GENERATE NEW COMPLEX RANDOM PASSWORD
                     -----------
                     Parameter Length: 24
                     Parameter AsClearText: True

                     Default settings: at least 2 special char, 2 digits and 2 letters.

                     round 12: Quotas reinitialized.

                     final: password kept as clear text.
                     }
Source             : HmD_New-RandomComplexPasword
TimeGenerated      : 09/10/2024 14:29:55
TimeWritten        : 09/10/2024 14:29:55
UserName           :

Index              : 7
EntryType          : Information
InstanceId         : 0
Message            : Running Hello My DIR! Edition 1.1.0.

                     Event Log "HelloMyDir" successfully created in "Applications and Services Logs"

                     All prerequesites are fullfilled. Parameters for this run:
                     > Prepare: False
                     > UpdateConfigFile: False
                     > AddDC: False

                     Script will now call mode: Create new Domain.

Category           : (0)
CategoryNumber     : 0
ReplacementStrings : {Running Hello My DIR! Edition 1.1.0.

                     Event Log "HelloMyDir" successfully created in "Applications and Services Logs"

                     All prerequesites are fullfilled. Parameters for this run:
                     > Prepare: False
                     > UpdateConfigFile: False
                     > AddDC: False

                     Script will now call mode: Create new Domain.
                     }
Source             : HmD_Invoke-HelloMyDIR
TimeGenerated      : 09/10/2024 14:27:28
TimeWritten        : 09/10/2024 14:27:28
UserName           :

Index              : 6
EntryType          : Information
InstanceId         : 0
Message            : END: invoke-HelloMyDir

Category           : (0)
CategoryNumber     : 0
ReplacementStrings : {END: invoke-HelloMyDir
                     }
Source             : HmD_Invoke-HelloMyDIR
TimeGenerated      : 09/10/2024 14:26:48
TimeWritten        : 09/10/2024 14:26:48
UserName           :

Index              : 5
EntryType          : Information
InstanceId         : 0
Message            : EXECUTION MODE: FIRST RUN

                     asking for data:
                     Install a new forest: Yes
                     Forest - FullName: hardening.local
                     Forest - NetBIOS: HARDENING
                     Forest - FFL: 10
                     Forest - RecycleBin: Yes
                     Forest - PAM: No
                     Domain - Type: Root
                     Domain - FullName: hardening.local
                     Domain - NetBIOS: HARDENING
                     Domain - FFL: 10
                     Domain - Sysvol Path: C:\Windows\SYSVOL
                     Domain - NTDS Path: C:\Windows\NTDS
                     Install AD-Domain-Services: Yes
                     Install RSAT-AD-Tools: Yes
                     Install RSAT-DNS-Server: Yes
                     Install RSAT-DFS-Mgmt-Con: Yes
                     Install GPMC: Yes

                     File RunSetup.xml updated and saved.


Category           : (0)
CategoryNumber     : 0
ReplacementStrings : {EXECUTION MODE: FIRST RUN

                     asking for data:
                     Install a new forest: Yes
                     Forest - FullName: hardening.local
                     Forest - NetBIOS: HARDENING
                     Forest - FFL: 10
                     Forest - RecycleBin: Yes
                     Forest - PAM: No
                     Domain - Type: Root
                     Domain - FullName: hardening.local
                     Domain - NetBIOS: HARDENING
                     Domain - FFL: 10
                     Domain - Sysvol Path: C:\Windows\SYSVOL
                     Domain - NTDS Path: C:\Windows\NTDS
                     Install AD-Domain-Services: Yes
                     Install RSAT-AD-Tools: Yes
                     Install RSAT-DNS-Server: Yes
                     Install RSAT-DFS-Mgmt-Con: Yes
                     Install GPMC: Yes

                     File RunSetup.xml updated and saved.

                     }
Source             : HmD_Invoke-HelloMyDIR
TimeGenerated      : 09/10/2024 14:26:48
TimeWritten        : 09/10/2024 14:26:48
UserName           :

Index              : 4
EntryType          : Information
InstanceId         : 0
Message            : START: Get-HmDDomain

                     Called by: Invoke-HelloMyDIR

                     Previous choices:
                     > Domain Type:
                     > Domain Fullname: Hello.My.Dir
                     > Domain NetBIOS name: HELLO
                     > Domain Functional Level:
                     > Domain Join Group: LS-DLG-DomainJoin-Extended
                     > Domain Join User: DLGUSER01

                     Domain DFL is empty, forced to 10
                     Enter Pressed. DomainDFL is 10
                     Domain SYSVOL: C:\Windows\SYSVOL
                     Domain NTDS: C:\Windows\NTDS
                     Domain Join User: DLGUSER01
                     Domain Join Group: LS-DLG-DomainJoin-Extended

Category           : (0)
CategoryNumber     : 0
ReplacementStrings : {START: Get-HmDDomain

                     Called by: Invoke-HelloMyDIR

                     Previous choices:
                     > Domain Type:
                     > Domain Fullname: Hello.My.Dir
                     > Domain NetBIOS name: HELLO
                     > Domain Functional Level:
                     > Domain Join Group: LS-DLG-DomainJoin-Extended
                     > Domain Join User: DLGUSER01

                     Domain DFL is empty, forced to 10
                     Enter Pressed. DomainDFL is 10
                     Domain SYSVOL: C:\Windows\SYSVOL
                     Domain NTDS: C:\Windows\NTDS
                     Domain Join User: DLGUSER01
                     Domain Join Group: LS-DLG-DomainJoin-Extended
                     }
Source             : HmD_Get-HmDDomain
TimeGenerated      : 09/10/2024 14:26:44
TimeWritten        : 09/10/2024 14:26:44
UserName           :

Index              : 3
EntryType          : Information
InstanceId         : 0
Message            : START: Get-HmDForest

                     Called by: Invoke-HelloMyDIR

                     Previous choices:
                     > Forest Fullname: Hello.My.Dir
                     > Forest NetBIOS name: HELLO
                     > Forest Functional Level:
                     > Enable Recycle Bin:
                     > Enable PAM:

                     OSCaption is Microsoft Windows Server 2025 Standard, the Regex will be ^[(4-7)0]$

                     FFL is empty, forcing to 10


Category           : (0)
CategoryNumber     : 0
ReplacementStrings : {START: Get-HmDForest

                     Called by: Invoke-HelloMyDIR

                     Previous choices:
                     > Forest Fullname: Hello.My.Dir
                     > Forest NetBIOS name: HELLO
                     > Forest Functional Level:
                     > Enable Recycle Bin:
                     > Enable PAM:

                     OSCaption is Microsoft Windows Server 2025 Standard, the Regex will be ^[(4-7)0]$

                     FFL is empty, forcing to 10

                     }
Source             : HmD_Get-HmDForest
TimeGenerated      : 09/10/2024 14:26:37
TimeWritten        : 09/10/2024 14:26:37
UserName           :

Index              : 2
EntryType          : Information
InstanceId         : 0
Message            : Function caller: New-HmDRunSetupXml

                     New file creation: .\Configuration\RunSetup.xml

                     Encoding: UTF8
                     Indent: Yes (tabulation)

Category           : (0)
CategoryNumber     : 0
ReplacementStrings : {Function caller: New-HmDRunSetupXml

                     New file creation: .\Configuration\RunSetup.xml

                     Encoding: UTF8
                     Indent: Yes (tabulation)
                     }
Source             : HmD_New-XmlContent
TimeGenerated      : 09/10/2024 14:26:00
TimeWritten        : 09/10/2024 14:26:00
UserName           :

Index              : 1
EntryType          : Information
InstanceId         : 0
Message            : Running Hello My DIR! Edition 1.1.0.

                     Event Log "HelloMyDir" successfully created in "Applications and Services Logs"

                     All prerequesites are fullfilled. Parameters for this run:
                     > Prepare: True
                     > UpdateConfigFile: False
                     > AddDC: False

                     Script will now call mode: First Run.

Category           : (0)
CategoryNumber     : 0
ReplacementStrings : {Running Hello My DIR! Edition 1.1.0.

                     Event Log "HelloMyDir" successfully created in "Applications and Services Logs"

                     All prerequesites are fullfilled. Parameters for this run:
                     > Prepare: True
                     > UpdateConfigFile: False
                     > AddDC: False

                     Script will now call mode: First Run.
                     }
Source             : HmD_Invoke-HelloMyDIR
TimeGenerated      : 09/10/2024 14:26:00
TimeWritten        : 09/10/2024 14:26:00
UserName           :
```
The server reboot and all work's great.

**Comment by LoicVeirman** [comment]
Thanks Jerome, I have an issue opened on this - I’ll get this one open too and will close once I get time to work on this false reporting from the script 😉

De : Jérôme Bezet-Torres [Alumni - MVP] ***@***.***>
Date : mercredi, 9 octobre 2024 à 14:44
À : LoicVeirman/Hello-My-Dir ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [LoicVeirman/Hello-My-Dir] Error On windows Server 2025 Install-binaries (Issue #9)

CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

Describe the bug
During the first stage to install binaries the script return error on installing binarres

Windows Server Version : 2025
OS Install English with french keyboard

image.png (view on web)<https://github.com/user-attachments/assets/1655aadd-149f-49ae-a532-c0eeeeb205f6>
In Powershell command Get-EventLog -LogName "HelloMyDir" | fl

Index              : 9

EntryType          : Information

InstanceId         : 0

Message            : USE CASE: The domain is to be installed



                     Error: Parameter set cannot be resolved using the specified named parameters.



                     Error: Parameter set cannot be resolved using the specified named parameters.



                     Error: Parameter set cannot be resolved using the specified named parameters.



                     Error: Parameter set cannot be resolved using the specified named parameters.



                     Error: Parameter set cannot be resolved using the specified named parameters.

                     Installation completed. The server will now reboot.



Category           : (0)

CategoryNumber     : 0

ReplacementStrings : {USE CASE: The domain is to be installed



                     Error: Parameter set cannot be resolved using the specified named parameters.



                     Error: Parameter set cannot be resolved using the specified named parameters.



                     Error: Parameter set cannot be resolved using the specified named parameters.



                     Error: Parameter set cannot be resolved using the specified named parameters.



                     Error: Parameter set cannot be resolved using the specified named parameters.

                     Installation completed. The server will now reboot.

                     }

Source             : HmD_Invoke-HelloMyDIR

TimeGenerated      : 09/10/2024 14:30:42

TimeWritten        : 09/10/2024 14:30:42

UserName           :



Index              : 8

EntryType          : Information

InstanceId         : 0

Message            : GENERATE NEW COMPLEX RANDOM PASSWORD

                     -----------

                     Parameter Length: 24

                     Parameter AsClearText: True



                     Default settings: at least 2 special char, 2 digits and 2 letters.



                     round 12: Quotas reinitialized.



                     final: password kept as clear text.



Category           : (0)

CategoryNumber     : 0

ReplacementStrings : {GENERATE NEW COMPLEX RANDOM PASSWORD

                     -----------

                     Parameter Length: 24

                     Parameter AsClearText: True



                     Default settings: at least 2 special char, 2 digits and 2 letters.



                     round 12: Quotas reinitialized.



                     final: password kept as clear text.

                     }

Source             : HmD_New-RandomComplexPasword

TimeGenerated      : 09/10/2024 14:29:55

TimeWritten        : 09/10/2024 14:29:55

UserName           :



Index              : 7

EntryType          : Information

InstanceId         : 0

Message            : Running Hello My DIR! Edition 1.1.0.



                     Event Log "HelloMyDir" successfully created in "Applications and Services Logs"



                     All prerequesites are fullfilled. Parameters for this run:

                     > Prepare: False

                     > UpdateConfigFile: False

                     > AddDC: False



                     Script will now call mode: Create new Domain.



Category           : (0)

CategoryNumber     : 0

ReplacementStrings : {Running Hello My DIR! Edition 1.1.0.



                     Event Log "HelloMyDir" successfully created in "Applications and Services Logs"



                     All prerequesites are fullfilled. Parameters for this run:

                     > Prepare: False

                     > UpdateConfigFile: False

                     > AddDC: False



                     Script will now call mode: Create new Domain.

                     }

Source             : HmD_Invoke-HelloMyDIR

TimeGenerated      : 09/10/2024 14:27:28

TimeWritten        : 09/10/2024 14:27:28

UserName           :



Index              : 6

EntryType          : Information

InstanceId         : 0

Message            : END: invoke-HelloMyDir



Category           : (0)

CategoryNumber     : 0

ReplacementStrings : {END: invoke-HelloMyDir

                     }

Source             : HmD_Invoke-HelloMyDIR

TimeGenerated      : 09/10/2024 14:26:48

TimeWritten        : 09/10/2024 14:26:48

UserName           :



Index              : 5

EntryType          : Information

InstanceId         : 0

Message            : EXECUTION MODE: FIRST RUN



                     asking for data:

                     Install a new forest: Yes

                     Forest - FullName: hardening.local

                     Forest - NetBIOS: HARDENING

                     Forest - FFL: 10

                     Forest - RecycleBin: Yes

                     Forest - PAM: No

                     Domain - Type: Root

                     Domain - FullName: hardening.local

                     Domain - NetBIOS: HARDENING

                     Domain - FFL: 10

                     Domain - Sysvol Path: C:\Windows\SYSVOL

                     Domain - NTDS Path: C:\Windows\NTDS

                     Install AD-Domain-Services: Yes

                     Install RSAT-AD-Tools: Yes

                     Install RSAT-DNS-Server: Yes

                     Install RSAT-DFS-Mgmt-Con: Yes

                     Install GPMC: Yes



                     File RunSetup.xml updated and saved.





Category           : (0)

CategoryNumber     : 0

ReplacementStrings : {EXECUTION MODE: FIRST RUN



                     asking for data:

                     Install a new forest: Yes

                     Forest - FullName: hardening.local

                     Forest - NetBIOS: HARDENING

                     Forest - FFL: 10

                     Forest - RecycleBin: Yes

                     Forest - PAM: No

                     Domain - Type: Root

                     Domain - FullName: hardening.local

                     Domain - NetBIOS: HARDENING

                     Domain - FFL: 10

                     Domain - Sysvol Path: C:\Windows\SYSVOL

                     Domain - NTDS Path: C:\Windows\NTDS

                     Install AD-Domain-Services: Yes

                     Install RSAT-AD-Tools: Yes

                     Install RSAT-DNS-Server: Yes

                     Install RSAT-DFS-Mgmt-Con: Yes

                     Install GPMC: Yes



                     File RunSetup.xml updated and saved.



                     }

Source             : HmD_Invoke-HelloMyDIR

TimeGenerated      : 09/10/2024 14:26:48

TimeWritten        : 09/10/2024 14:26:48

UserName           :



Index              : 4

EntryType          : Information

InstanceId         : 0

Message            : START: Get-HmDDomain



                     Called by: Invoke-HelloMyDIR



                     Previous choices:

                     > Domain Type:

                     > Domain Fullname: Hello.My.Dir

                     > Domain NetBIOS name: HELLO

                     > Domain Functional Level:

                     > Domain Join Group: LS-DLG-DomainJoin-Extended

                     > Domain Join User: DLGUSER01



                     Domain DFL is empty, forced to 10

                     Enter Pressed. DomainDFL is 10

                     Domain SYSVOL: C:\Windows\SYSVOL

                     Domain NTDS: C:\Windows\NTDS

                     Domain Join User: DLGUSER01

                     Domain Join Group: LS-DLG-DomainJoin-Extended



Category           : (0)

CategoryNumber     : 0

ReplacementStrings : {START: Get-HmDDomain



                     Called by: Invoke-HelloMyDIR



                     Previous choices:

                     > Domain Type:

                     > Domain Fullname: Hello.My.Dir

                     > Domain NetBIOS name: HELLO

                     > Domain Functional Level:

                     > Domain Join Group: LS-DLG-DomainJoin-Extended

                     > Domain Join User: DLGUSER01



                     Domain DFL is empty, forced to 10

                     Enter Pressed. DomainDFL is 10

                     Domain SYSVOL: C:\Windows\SYSVOL

                     Domain NTDS: C:\Windows\NTDS

                     Domain Join User: DLGUSER01

                     Domain Join Group: LS-DLG-DomainJoin-Extended

                     }

Source             : HmD_Get-HmDDomain

TimeGenerated      : 09/10/2024 14:26:44

TimeWritten        : 09/10/2024 14:26:44

UserName           :



Index              : 3

EntryType          : Information

InstanceId         : 0

Message            : START: Get-HmDForest



                     Called by: Invoke-HelloMyDIR



                     Previous choices:

                     > Forest Fullname: Hello.My.Dir

                     > Forest NetBIOS name: HELLO

                     > Forest Functional Level:

                     > Enable Recycle Bin:

                     > Enable PAM:



                     OSCaption is Microsoft Windows Server 2025 Standard, the Regex will be ^[(4-7)0]$



                     FFL is empty, forcing to 10





Category           : (0)

CategoryNumber     : 0

ReplacementStrings : {START: Get-HmDForest



                     Called by: Invoke-HelloMyDIR



                     Previous choices:

                     > Forest Fullname: Hello.My.Dir

                     > Forest NetBIOS name: HELLO

                     > Forest Functional Level:

                     > Enable Recycle Bin:

                     > Enable PAM:



                     OSCaption is Microsoft Windows Server 2025 Standard, the Regex will be ^[(4-7)0]$



                     FFL is empty, forcing to 10



                     }

Source             : HmD_Get-HmDForest

TimeGenerated      : 09/10/2024 14:26:37

TimeWritten        : 09/10/2024 14:26:37

UserName           :



Index              : 2

EntryType          : Information

InstanceId         : 0

Message            : Function caller: New-HmDRunSetupXml



                     New file creation: .\Configuration\RunSetup.xml



                     Encoding: UTF8

                     Indent: Yes (tabulation)



Category           : (0)

CategoryNumber     : 0

ReplacementStrings : {Function caller: New-HmDRunSetupXml



                     New file creation: .\Configuration\RunSetup.xml



                     Encoding: UTF8

                     Indent: Yes (tabulation)

                     }

Source             : HmD_New-XmlContent

TimeGenerated      : 09/10/2024 14:26:00

TimeWritten        : 09/10/2024 14:26:00

UserName           :



Index              : 1

EntryType          : Information

InstanceId         : 0

Message            : Running Hello My DIR! Edition 1.1.0.



                     Event Log "HelloMyDir" successfully created in "Applications and Services Logs"



                     All prerequesites are fullfilled. Parameters for this run:

                     > Prepare: True

                     > UpdateConfigFile: False

                     > AddDC: False



                     Script will now call mode: First Run.



Category           : (0)

CategoryNumber     : 0

ReplacementStrings : {Running Hello My DIR! Edition 1.1.0.



                     Event Log "HelloMyDir" successfully created in "Applications and Services Logs"



                     All prerequesites are fullfilled. Parameters for this run:

                     > Prepare: True

                     > UpdateConfigFile: False

                     > AddDC: False



                     Script will now call mode: First Run.

                     }

Source             : HmD_Invoke-HelloMyDIR

TimeGenerated      : 09/10/2024 14:26:00

TimeWritten        : 09/10/2024 14:26:00

UserName           :

The server reboot and all work's great.
